### ISSUE TITLE
More documentation is needed

### ISSUE THREAD

**Issue by zxffffffff** [neogeek/rhythm-game-utilities#70]
What can and can't be done for this project

- Godot C# support?
- Can I parse LyRiCs in LRC(LyRiCs) format?

**Comment by neogeek** [comment]
I'm currently working on building out the feature set of this project so some things are in flux. But the goal is to have Godot support for both GDScript and Mono C# projects. I have not looked into the LRC file format but it looks easy enough to implement. It would be useful when I setup MIDI note/channel parsing as I won't have a way to read lyrics.

Thank you for checking out my project!

**Comment by neogeek** [comment]
Godot C# support has been added! But again, like everything else in this repo, it's very much in flux. I am not sold on the install/setup process, as I would prefer it to be a nuget package, but I'm not sure that's an option given how the library is set up.

**Comment by zxffffffff** [comment]
I am trying to add to the Godot c # project, according to the readme I quickly add code, found NativeLibrary. SetDllImportResolver failed to perform, wait me again after debugging success to feedback ：）

**Comment by neogeek** [comment]
I'm going to switch the C# library to C# only (and no longer include the C++ libraries). This will make it so you will be able to install the C# library via a nuget package and not have to configure anything. I have a branch in the works, but I still need to test everything before I commit to it.

**Comment by zxffffffff** [comment]
It's better not to do it this way. Having two identical copies of C++/C# code isn't ideal, and it won't support Godot's native GDScript.

Godot actually has `C++ Modules` and `GDExtension` specifically for plugin extensions. By registering C++ functions with `ClassDB`, you can expose them to other scripts at the same time.

- <https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/index.html>
- <https://docs.godotengine.org/en/stable/classes/class_classdb.html>

I'd love to contribute code, but I just don't have much free time at the moment.

**Comment by zxffffffff** [comment]
According to the *GODOT Community Poll 2024*, 76.5% of developers use GDScript, while 17.3% use C#.

- <https://godotengine.org/article/godot-community-poll-2024/>

**Comment by neogeek** [comment]
I took a crack at learning how to make native GDExtension plugins and I think I have a better understanding of how it works. I still haven't loaded in the library, just learned how to author, build and import basic plugins. I'll take a pass at loading in a single header file tomorrow.

**Comment by neogeek** [comment]
I've made progress loading the library into my Godot plugin. Not sure how much more time I can dedicate to it this weekend, but I'll let you know if I make anymore progress.

**Comment by neogeek** [comment]
I managed to build out all but one method in the Godot plugin (holding off on that one until I've learned more about how to dev in Godot). I've tested it successfully on both Windows and macOS. The next step is to figure out the right way to distribute the compiled package.

**Comment by zxffffffff** [comment]
Providing .dll and .dylib directly is probably the easiest and most direct way, and developers can use it however they want.
